GET http://localhost:8080

###

POST http://localhost:8080/new-message
Content-Type: application/json

{
  "attachments": [],
  "avatar_url": "https://i.groupme.com/123456789",
  "created_at": 1302623328,
  "group_id": "1234567890",
  "id": "1234567890",
  "name": "John",
  "sender_id": "12345",
  "sender_type": "user",
  "source_guid": "GUID",
  "system": false,
  "text": "Hello world ☃☃ @LikePolice remind me to watch this",
  "user_id": "1234567890"
}